language: java
sudo: required
dist: trusty
os:
- linux
- osx
env:
  global:
  - GRAAL_VERSION="1.0.0-rc6"
before_install:
- if [ $TRAVIS_OS_NAME = osx ]; then brew install yarn; gem update --system; export GRAAL_OS=macos; else export GRAAL_OS=${TRAVIS_OS_NAME}; fi
install:
- yarn install
- node ./download-jar.js
- export GRAAL_URL="https://github.com/oracle/graal/releases/download/vm-$GRAAL_VERSION/graalvm-ce-$GRAAL_VERSION-$GRAAL_OS-amd64.tar.gz"
- echo $GRAAL_URL
- curl --fail -s -S -L $GRAAL_URL | tar -xz
- if [ $TRAVIS_OS_NAME = osx ]; then
    export GRAAL_NATIVE_IMAGE_PATH=graalvm-ce-${GRAAL_VERSION}/Contents/Home/bin/native-image;
  else
    export GRAAL_NATIVE_IMAGE_PATH=graalvm-ce-${GRAAL_VERSION}/bin/native-image;
  fi
script:
- ${GRAAL_NATIVE_IMAGE_PATH} -H:+JNI --no-server -H:+ReportUnsupportedElementsAtRuntime
    -H:IncludeResourceBundles=com.google.javascript.rhino.Messages
    -H:IncludeResourceBundles=org.kohsuke.args4j.Messages
    -H:IncludeResourceBundles=org.kohsuke.args4j.spi.Messages
    -H:IncludeResourceBundles=com.google.javascript.jscomp.parsing.ParserConfig
    -H:ReflectionConfigurationFiles=reflection-config.json
    -H:IncludeResources='(externs.zip)|(.*(js|txt))'
    -jar compiler.jar
- ./compiler --version | grep 'Version:'
- ./compiler --help | grep 'Basic Usage:'
- echo "console.log('hello');" | ./compiler | grep 'console.log'
before_deploy:
- node prepare-publish.js
deploy:
  skip_cleanup: true
  provider: npm
  email: chadkillingsworth@gmail.com
  on:
    repo: ChadKillingsworth/closure-compiler-graal
    branch: master
  api_key:
    secure: LkXlXGXx5QtGrhprPDlJw1pa6cydNZlxZPWs8zotSK9hHl1q7MJK8GnJKsUfJG3Vmuf0sJw+T88dUbtnOSxmrhv1w34AO6sDcq6eyuZxIJ7/aSqss2ovulrGyTqLU3c8ms3FgPCUgrnDroYCJuPqZ/vQJXHUBXcNOisKAwUtD3Uwusqs9JM7J3kzTFRTjHFQAdIWF20Ui/uu8Csn4Evwub5y9PTZUD6HUrmNHaXDfSwdl+ClwbhXfsgy8BJhHN1krwhOv9+xwk9GoEbstRYUxdVl6e0Yx3H4JpV+1H7OFmMttY2qqB6IKXb8CUeVYxFCGmASE/FJPfnFd4wsmt4yfm3b/73EIze29caz+abcftMz6Q5zGsN40rKH8MlQscmXwTMtYCuImDlTrjdFCwiL0brJ890IUmyou+TKY9n96YnqkO6b5IQV0trRSEQ7izlaEjNiZmVie4D+d2whsvj8ePVLRitf/t1m0AGEcz1Cb8WjSmG8p3Zvw5hwoA4XlUt+v1zpaTbo7EWFOecXSaLwOtvW+X5NVCZPVB5QCNPQNqSM3nb7WUG3u8/zcdO/yBT9pOKCMHQnqMsE65UYxKK/fUWiCsuORBAjFaHYhCowxl6COytjxNy2vr8bG1VWsKwwd/FqunpEk3UPIAH2MYEQbCXVBKosomQmuq4I+2g7lcM=
