language: java
python:
- '2.7'
addons:
  apt:
    packages:
    - python-pip
    - python-virtualenv
    - wget
    - mercurial
sudo: required
dist: trusty
os:
- linux
- osx
env:
  global:
  - JVMCI_VERSION="jvmci-0.46"
  - JDK8_UPDATE_VERSION="172"
before_install:
- if [ $TRAVIS_OS_NAME = osx ]; then brew install yarn; gem update --system; fi
install:
- |
  yarn install
  node ./download-jar.js
- |
  export MX_PATH=${TRAVIS_BUILD_DIR}/../mx
  git clone https://github.com/graalvm/mx.git ${MX_PATH}
  export PATH=${PATH}:${MX_PATH}
- |
  export JVMCI_JAVA=${TRAVIS_BUILD_DIR}/../jvmci-8/bin/java
  if [ $TRAVIS_OS_NAME = osx ]; then
    brew tap caskroom/versions;
    brew cask install java8;
    export JAVA_HOME=/Library/Java/JavaVirtualMachines/$(ls -l1 /Library/Java/JavaVirtualMachines | tail -1)/Contents/Home;
    git clone https://github.com/graalvm/graal-jvmci-8.git ../graal-jvmci-8;
    cd ../graal-jvmci-8;
    git checkout ${JVMCI_VERSION};
    mx build;
    if [ -d "${TRAVIS_BUILD_DIR}/../jvmci-8" ]; then rm -rf ${TRAVIS_BUILD_DIR}/../jvmci-8; fi
    cp -R ${TRAVIS_BUILD_DIR}/../graal-jvmci-8/jdk1.8.0_*/darwin-amd64/product/Contents/Home ${TRAVIS_BUILD_DIR}/../jvmci-8;
    cd ${TRAVIS_BUILD_DIR};
  else
    JDK_TAR=${TRAVIS_BUILD_DIR}/../jdk.tar.gz;
    wget https://github.com/graalvm/openjdk8-jvmci-builder/releases/download/${JVMCI_VERSION}/openjdk-8u${JDK8_UPDATE_VERSION}-${JVMCI_VERSION}-linux-amd64.tar.gz -O ${JDK_TAR};
    tar -C ${TRAVIS_BUILD_DIR}/.. -xzf ${JDK_TAR};
    if [ -d "${TRAVIS_BUILD_DIR}/../jvmci-8" ]; then rm -rf ${TRAVIS_BUILD_DIR}/../jvmci-8; fi
    cp -R ${TRAVIS_BUILD_DIR}/../openjdk1.8.0_${JDK8_UPDATE_VERSION}-${JVMCI_VERSION} ${TRAVIS_BUILD_DIR}/../jvmci-8;
  fi
  export JAVA_HOME=${TRAVIS_BUILD_DIR}/../jvmci-8
  export EXTRA_JAVA_HOMES=${JAVA_HOME} # JDK8 must be placed in EXTRA_JAVA_HOME
script:
- echo ${JAVA_HOME}
- echo ${EXTRA_JAVA_HOMES}
- "${JAVA_HOME}/bin/java -version"
- cd ${TRAVIS_BUILD_DIR}/graal && mx -v --primary-suite-path substratevm build
- |
  cd ${TRAVIS_BUILD_DIR}/graal/substratevm
  mx -v native-image -H:+JNI --no-server \
    -H:+ReportUnsupportedElementsAtRuntime \
    -H:IncludeResourceBundles=com.google.javascript.rhino.Messages \
    -H:IncludeResourceBundles=org.kohsuke.args4j.Messages \
    -H:IncludeResourceBundles=org.kohsuke.args4j.spi.Messages \
    -H:IncludeResourceBundles=com.google.javascript.jscomp.parsing.ParserConfig \
    -H:ReflectionConfigurationFiles=${TRAVIS_BUILD_DIR}/reflection-config.json \
    -H:IncludeResources='(externs.zip)|(.*(js|txt))' \
    -jar ${TRAVIS_BUILD_DIR}/compiler.jar
- mv ${TRAVIS_BUILD_DIR}/graal/substratevm/compiler ${TRAVIS_BUILD_DIR}/compiler
- cd ${TRAVIS_BUILD_DIR}
- "./compiler --version"
- "./compiler --help"
- echo "console.log('hello');" | ./compiler
after_failure:
- cat hs_err*
before_deploy:
- node prepare-publish.js
deploy:
  skip_cleanup: true
  provider: npm
  email: chadkillingsworth@gmail.com
  on:
    repo: ChadKillingsworth/closure-compiler-graal
    branch: master
  api_key:
    secure: LkXlXGXx5QtGrhprPDlJw1pa6cydNZlxZPWs8zotSK9hHl1q7MJK8GnJKsUfJG3Vmuf0sJw+T88dUbtnOSxmrhv1w34AO6sDcq6eyuZxIJ7/aSqss2ovulrGyTqLU3c8ms3FgPCUgrnDroYCJuPqZ/vQJXHUBXcNOisKAwUtD3Uwusqs9JM7J3kzTFRTjHFQAdIWF20Ui/uu8Csn4Evwub5y9PTZUD6HUrmNHaXDfSwdl+ClwbhXfsgy8BJhHN1krwhOv9+xwk9GoEbstRYUxdVl6e0Yx3H4JpV+1H7OFmMttY2qqB6IKXb8CUeVYxFCGmASE/FJPfnFd4wsmt4yfm3b/73EIze29caz+abcftMz6Q5zGsN40rKH8MlQscmXwTMtYCuImDlTrjdFCwiL0brJ890IUmyou+TKY9n96YnqkO6b5IQV0trRSEQ7izlaEjNiZmVie4D+d2whsvj8ePVLRitf/t1m0AGEcz1Cb8WjSmG8p3Zvw5hwoA4XlUt+v1zpaTbo7EWFOecXSaLwOtvW+X5NVCZPVB5QCNPQNqSM3nb7WUG3u8/zcdO/yBT9pOKCMHQnqMsE65UYxKK/fUWiCsuORBAjFaHYhCowxl6COytjxNy2vr8bG1VWsKwwd/FqunpEk3UPIAH2MYEQbCXVBKosomQmuq4I+2g7lcM=
